### ISSUE TITLE
#1 OpenAI API Integration

### ISSUE THREAD

**Issue by OswaldHaidinger** [OswaldHaidinger/Privacy-Pal#1]
## Value proposition

As an Internet user
I want a possibility to read the Terms & Conditions and Privacy Policies and get all relevant information
So that I can understand if my Data is being handled well and I can learn the Terms of service without having to read the whole thing.

## Description

Be able to paste the contract text or the name of the company/product in order to get a summarised version of it.
<img width="950" alt="image" src="https://github.com/OswaldHaidinger/Privacy-Pal/assets/164864733/c8c7a446-f35e-4004-9c8e-fc66afbd92ae">

## Acceptance criteria

- [ ] On the Home Screen there is a Text field where I can paste in the contract and below there is a button to submit it
- [ ] When it is clicked the user is shown a loading screen for the time it takes to be processed (the text is send to Open AI API)
- [ ] On the loading screen, show a pictogram to indicate it is processing and write a small text to let the user know
- [ ] When the API send the response back, show the user the summary of the contract they pasted earlier (this is generated by Chat GPT without any extra prompts (for now))
- [ ] On the top of the summary screen, have a button in the top left to go back to the Home Screen

## Tasks

- [ ] Create a project file for the App
- [ ] Integrate the API so that it can receive the pasted text and return a summary of it
- [ ] Have a basic page layout that allows for a seamless experience of the above mentioned features
